version: '3.4'

networks:
  db_network: {}

services:

  db:
    image: mariadb
    container_name: mariadb-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_PASSWORD}
    networks:
      - db_network
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ${CONFIG_FOLDER}/mariadb:/var/lib/mysql