
version: '3.5'

networks:
  nextcloud_network:
    name: nextcloud_network
  db_network:
    external:
      name: mariadb_db_network
  db_network:
    external:
      name: net

services:
  app:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    networks:
      - db_network
      - nextcloud_network
      - net
    volumes:
      - ${CONFIG_FOLDER}/nextcloud-fpm/html:/var/www/html:rw
      - ${DISK_FOLDER}:/srvdisk:rw
    environment:      
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - NEXTCLOUD_TRUSTED_DOMAINS='${DOMEN}'
      - VIRTUAL_HOST='${DOMEN}'
      - LETSENCRYPT_HOST='${DOMEN}'      
